name: Build Installer
 
on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup Inno Setup
      uses: mhurik/setup-inno-setup@v1
      with:
        is-version: '6.1.0'
 
    - name: Build Installer
      run: |
        BuildFaToolBox.bat
        #iscc your-script.iss
